# Generated by Django 6.1 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad_compra',
            field=models.DecimalField(decimal_places=2, default=1, help_text="En la misma unidad de medida (ej: si Unidad es 'gr', cargar la compra en gramos).", max_digits=10, verbose_name='Cantidad comprada'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Precio pagado por la cantidad indicada en 'Cantidad comprada'.", max_digits=12, verbose_name='Costo de la última compra'),
        ),
    ]
