# Generated by Django 6.1 on 2026-08-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura preimpresa')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('total_almacenado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto total almacenado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
